[package]

name = "healsim"
version = "0.0.1"
authors = ["Andr√© Eriksson <eandre@gmail.com>"]

[lib]
name = "simlib"
path = "src/simlib/lib.rs"

[[bin]]
name = "healsim"
path = "src/healsim/main.rs"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"
